name: cotwcastmate
description: Companion for the game Call of the Wild theAngler

publish_to: 'none'

version: 1.0.8+9

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_xlider: ^3.0.2
  async: 2.11.0
  auto_size_text: 3.0.0
  blurrycontainer: 2.1.0
  collection: ^1.18.0
  device_info_plus: ^10.1.0
  easy_localization: ^3.0.7
  easy_rich_text: ^2.1.0
  equatable: 2.0.5
  expandable_page_view: 1.0.17
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_gen_runner: ^5.6.0
  flutter_lints: 4.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  latlng: 2.0.7
  logger: ^2.3.0
  map: 2.0.2
  omni_datetime_picker: ^2.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  simple_shadow: 0.3.1
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/
  assets:
    exclude:
      - assets/fonts/*
      - assets/translations/*
      - assets/graphics/maps/**/*

flutter:
  uses-material-design: true
  assets:
    - assets/raw/
    - assets/raw/maps/
    - assets/fonts/
    - assets/translations/
    - assets/graphics/icons/
    - assets/graphics/images/
    - assets/graphics/fish/
    - assets/graphics/reserves/
    - assets/graphics/maps/goldenridgereserve/1/
    - assets/graphics/maps/goldenridgereserve/2/
    - assets/graphics/maps/goldenridgereserve/3/
    - assets/graphics/maps/trollsporetnaturereserve/1/
    - assets/graphics/maps/trollsporetnaturereserve/2/
    - assets/graphics/maps/trollsporetnaturereserve/3/
    - assets/graphics/maps/aguasclarasmunicipio/1/
    - assets/graphics/maps/aguasclarasmunicipio/2/
    - assets/graphics/maps/aguasclarasmunicipio/3/
    - assets/graphics/maps/izilozasendulo/1/
    - assets/graphics/maps/izilozasendulo/2/
    - assets/graphics/maps/izilozasendulo/3/
  fonts:
    - family: Normal
      fonts:
        - asset: assets/fonts/Normal200.ttf
          weight: 200
        - asset: assets/fonts/Normal300.ttf
          weight: 300
        - asset: assets/fonts/Normal400.ttf
          weight: 400
        - asset: assets/fonts/Normal500.ttf
          weight: 500
        - asset: assets/fonts/Normal600.ttf
          weight: 600
        - asset: assets/fonts/Normal700.ttf
          weight: 700
    - family: Condensed
      fonts:
        - asset: assets/fonts/Condensed400.ttf
          weight: 400